name: MobArena
main: com.garbagemule.MobArena.MobArena
version: 0.94.4.4
softdepend: [Spout,Permissions,MultiVerse,XcraftGate,Towny,Heroes,MagicSpells]
commands:
    ma:
        description: Base command for MobArena
        usage: |
            YOU HAVE AN ERROR!
            Find the error in your server log, copy it into
            http://pastebin.com, and then paste the link
            in the IRC or on the forums.
    mobarena:
        description: Base command for MobArena
        usage: |
            YOU HAVE AN ERROR!
            Find the error in your server log, copy it into
            http://pastebin.com, and then paste the link
            in the IRC or on the forums.
permissions:
    mobarena.use:
        description: Gives access to usage commands
        default: true
        children:
            mobarena.use.join: true
            mobarena.use.spec: true
            mobarena.use.leave: true
            mobarena.use.signs: true
    mobarena.use.join:
        default: true
    mobarena.use.spec:
        default: true
    mobarena.use.leave:
        default: true
    
    mobarena.admin:
        description: Gives access to all admin commands
        default: op
        children:
            mobarena.admin.enable: true
            mobarena.admin.kick: true
            mobarena.admin.restore: true
            mobarena.admin.force.end: true
            mobarena.admin.force.start: true
            mobarena.admin.config.reload: true
    mobarena.admin.enable:
        description: Enable and disable MobArena and/or arenas.
        default: false
    mobarena.admin.kick:
        description: Kick a player from an arena.
        default: false
    mobarena.admin.restore:
        description: Restore a player's inventory.
        default: false
    mobarena.admin.force.end:
        description: Force end an arena.
        default: false
    mobarena.admin.force.start:
        description: Force start an arena.
        default: false
    mobarena.admin.config.reload:
        description: Reload the config-file.
        default: false
    
    mobarena.setup:
        description: Gives access to all setup commands
        default: op
        children:
            mobarena.setup.arena: true
            mobarena.setup.setarena: true
            mobarena.setup.addarena: true
            mobarena.setup.delarena: true
            mobarena.setup.protect: true
            mobarena.setup.editarena: true
            mobarena.setup.setregion: true
            mobarena.setup.expandregion: true
            mobarena.setup.showregion: true
            mobarena.setup.setlobbyregion: true
            mobarena.setup.expandlobbyregion: true
            mobarena.setup.setwarp: true
            mobarena.setup.spawnpoints: true
            mobarena.setup.addspawn: true
            mobarena.setup.delspawn: true
            mobarena.setup.containers: true
            mobarena.setup.addcontainer: true
            mobarena.setup.delcontainer: true
            mobarena.setup.leaderboards: true
            mobarena.setup.signs: true
            mobarena.setup.checkdata: true
            mobarena.setup.autogenerate: true
            mobarena.setup.autodegenerate: true
    mobarena.setup.arena:
        description: Check which arena is the currently selected arena.
        default: false
    mobarena.setup.setarena:
        description: Select a new arena.
        default: false
    mobarena.setup.addarena:
        description: Add a new arena node.
        default: false
    mobarena.setup.delarena:
        description: Delete an arena.
        default: false
    mobarena.setup.protect:
        description: Turn arena protection on/off.
        default: false
    mobarena.setup.editarena:
        description: Turn editmode on/off.
        default: false
    mobarena.setup.setregion:
        description: Set region points p1/p2.
        default: false
    mobarena.setup.expandregion:
        description: Expand arena region.
        default: false
    mobarena.setup.showregion:
        description: Show arena region.
        default: false
    mobarena.setup.setlobbyregion:
        description: Set lobby region points l1/l2.
        default: false
    mobarena.setup.expandlobbyregion:
        description: Expand lobby region.
        default: false
    mobarena.setup.setwarp:
        description: Set warp points arena/lobby/spectator.
        default: false
    mobarena.setup.spawnpoints:
        description: List all spawnpoints.
        default: false
    mobarena.setup.addspawn:
        description: Add a new spawnpoint.
        default: false
    mobarena.setup.delspawn:
        description: Delete a spawnpoint.
        default: false
    mobarena.setup.containers:
        description: List all containers.
        default: false
    mobarena.setup.addcontainer:
        description: Add a new container.
        default: false
    mobarena.setup.delcontainer:
        description: Delete a container.
        default: false
    mobarena.setup.leaderboards:
        description: Set up leaderboards.
        default: false
    mobarena.setup.checkdata:
        description: Check which points need to be set up.
        default: false
    mobarena.setup.autogenerate:
        description: Auto-generate an arena.
        default: false
    mobarena.setup.autodegenerate:
        description: Auto-degenerate an arena.
        default: false